### PR TITLE
RP2040 constructor rework

### LINKED ISSUE #18: RP2040 interface - redo
@Intubun 

Yeah I think so too... Its much easier, if all Libs of a person are standardised. Im currently on the MCP_DAC Lib. The changes are working so far, but I need to change a whole lot, if I want to use the RP2040, since the "SPIClass" of the Pico is called "SPIClassRP2040" which is defenetly not great... I will also edit the ESP32 Class, but since I dont have much experience nor the hardware, thats something you need to validate...

_Originally posted by @Intubun in https://github.com/RobTillaart/ADS1X15/issues/46#issuecomment-1281849601_

### PR DESCRIPTION
**Pull request by Intubun**
Issue #18 
Should work right out of the box...
Validated with MCP4822 and RPi Pico

### CODE REVIEW

**Comment by Intubun** [comment]
Yeehaw! It worked the first time!

**Comment by RobTillaart** [comment]
@Intubun 
Think you did a good job. 
In the begin() function you have
```cpp
    #elif defined(ARDUINO_ARCH_RP2040)
    mySPI->end();
    mySPI->begin();
    #else              // generic hardware SPI
    mySPI = &SPI;
    mySPI->end();
    mySPI->begin();
    #endif
```
I think this must be replaced by 
```cpp
    #else              // generic hardware SPI
    mySPI->end();
    mySPI->begin();
    #endif
```
mySPI is already set in the constructor and would be overwritten in case of non-RP2040

Should work for RP2040 too.

**Comment by Intubun** [comment]
Oh.. Forgot one there... Well another commit is necessary...

**Comment by RobTillaart** [comment]
In the derived classes in the **mcp_dac.h** you use many times the conditional construct.
```cpp
class MCP4801 : public MCP_DAC
{
public:
  #if defined(ARDUINO_ARCH_RP2040)
  MCP4801(uint8_t dataOut = 255, uint8_t clock = 255, SPIClassRP2040 *inSPI = &SPI);
  #else
  MCP4801(uint8_t dataOut = 255, uint8_t clock = 255, SPIClass *inSPI = &SPI);
  #endif
};
```

technically this is OK, but in the **mcp_dac.cpp** you do it with one **#if RP2040** in a big block.
I like that much better as when I read the code I do not need to switch context that often.
(it is not wrong, but the ".cpp way" is far easier to maintain imho.

**Comment by RobTillaart** [comment]
No further remarks, thanks!

**Comment by Intubun** [comment]
Your requested changes are done...

**Comment by RobTillaart** [comment]
Great work, 
I will update the version and release later today / tomorrow.

**Pull request merged**
